# Generated by Django 2.1.2 on 2018-11-08 08:17

from django.db import migrations, models

def add_languages(apps, schema_editor):
    languages = ["Afrikaans",
                 "Albanian",
                 "Arabic",
                 "Armenian",
                 "Basque",
                 "Bengali",
                 "Bulgarian",
                 "Catalan",
                 "Cambodian",
                 "Chinese (Mandarin)",
                 "Croatian",
                 "Czech",
                 "Danish",
                 "Dutch",
                 "English",
                 "Estonian",
                 "Fiji",
                 "Finnish",
                 "French",
                 "Georgian",
                 "German",
                 "Greek",
                 "Gujarati",
                 "Hebrew",
                 "Hindi",
                 "Hungarian",
                 "Icelandic",
                 "Indonesian",
                 "Irish",
                 "Italian",
                 "Japanese",
                 "Javanese",
                 "Korean",
                 "Latin",
                 "Latvian",
                 "Lithuanian",
                 "Macedonian",
                 "Malay",
                 "Malayalam",
                 "Maltese",
                 "Maori",
                 "Marathi",
                 "Mongolian",
                 "Nepali",
                 "Norwegian",
                 "Persian",
                 "Polish",
                 "Portuguese",
                 "Punjabi",
                 "Quechua",
                 "Romanian",
                 "Russian",
                 "Samoan",
                 "Serbian",
                 "Slovak",
                 "Slovenian",
                 "Spanish",
                 "Swahili",
                 "Swedish",
                 "Tamil",
                 "Tatar",
                 "Telugu",
                 "Thai",
                 "Tibetan",
                 "Tonga",
                 "Turkish",
                 "Ukrainian",
                 "Urdu",
                 "Uzbek",
                 "Vietnamese",
                 "Welsh",
                 "Xhosa"]
    Language = apps.get_model("users", "Language")
    Language.objects.all().delete()
    for lang in languages:
        l = Language(name=lang)
        l.save()

class Migration(migrations.Migration):
    
    dependencies = [
                    ('users', '0001_initial')
    ]

    operations = [
                   migrations.RunPython(add_languages)
    ]
