# Generated by Django 2.1.2 on 2018-11-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('ENG', 'English'), ('SPN', 'Spanish'), ('FRN', 'French'), ('GER', 'German')], default='English', max_length=10),
        ),
    ]
