# Generated by Django 2.1.2 on 2018-11-04 23:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181104_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_preference',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('FRE', 'French'), ('GER', 'German')], default='English', max_length=3),
        ),
    ]
