# Generated by Django 2.1.2 on 2018-11-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181105_0523'),
    ]

    operations = [
    ]
